fix/Return the same handle when an NFS File handle is provided to safeNfs.open
maidsafe/beaker-plugin-safe-app pull request #89
Opened 2017-09-26 18:29 UTC by bochaco

2017-09-26 18:53 UTC, hunterlester approved these changes

2017-10-03 07:59 UTC, joshuef requested changes
Works. Tested via: https://github.com/maidsafe/safe_browser/pull/198

Only thing is to update the docs to clarify the return is the same, I think

2017-10-03 07:59 UTC, joshuef commented on src/api/emulations/nfs.js
> +        return genHandle(nfsObj.app, file);
If we're returning the same file handle, let's update the docs above to make this clear.

2017-10-03 12:40 UTC, joshuef approved these changes

2017-10-03 18:16 UTC, merged